package com.tzz.ws.cxf.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.tzz.ws.cxf.service.WsOrdersService;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-14T14:30:40.949+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebServiceClient(name = "wsOrdersServiceImpl", 
                  wsdlLocation = "http://localhost:8080/web-demo/cxf/wsOrdersService?wsdl",
                  targetNamespace = "http://impl.service.cxf.ws.tzz.com/") 
public class WsOrdersServiceImpl extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.service.cxf.ws.tzz.com/", "wsOrdersServiceImpl");
    public final static QName WsOrdersServiceImplPort = new QName("http://impl.service.cxf.ws.tzz.com/", "WsOrdersServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/web-demo/cxf/wsOrdersService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WsOrdersServiceImpl.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/web-demo/cxf/wsOrdersService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WsOrdersServiceImpl(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsOrdersServiceImpl(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsOrdersServiceImpl() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WsOrdersServiceImpl(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WsOrdersServiceImpl(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WsOrdersServiceImpl(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WsOrdersService
     */
    @WebEndpoint(name = "WsOrdersServiceImplPort")
    public WsOrdersService getWsOrdersServiceImplPort() {
        return super.getPort(WsOrdersServiceImplPort, WsOrdersService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WsOrdersService
     */
    @WebEndpoint(name = "WsOrdersServiceImplPort")
    public WsOrdersService getWsOrdersServiceImplPort(WebServiceFeature... features) {
        return super.getPort(WsOrdersServiceImplPort, WsOrdersService.class, features);
    }

}
