package com.tzz.ws.cxf.service;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.4
 * 2016-01-14T14:30:40.897+08:00
 * Generated source version: 3.1.4
 * 
 */
@WebService(targetNamespace = "http://service.cxf.ws.tzz.com/", name = "WsOrdersService")
@XmlSeeAlso({ObjectFactory.class})
public interface WsOrdersService {

    @WebMethod
    @RequestWrapper(localName = "findAllOrders", targetNamespace = "http://service.cxf.ws.tzz.com/", className = "com.tzz.ws.cxf.service.FindAllOrders")
    @ResponseWrapper(localName = "findAllOrdersResponse", targetNamespace = "http://service.cxf.ws.tzz.com/", className = "com.tzz.ws.cxf.service.FindAllOrdersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.tzz.ws.cxf.service.Orders> findAllOrders();
}
